apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: backend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend # Nombre del contenedor 
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }} # Imagen del contenedor, usando variables del Helm chart
          imagePullPolicy: {{ .Values.image.pullPolicy }} # Política para descargar la imagen
          ports: # Puerto expuesto por el contenedor
            - containerPort: {{ .Values.service.port }}
          env: # Variables de entorno necesarias para la aplicación
            - name: SPRING_DB_HOST
              value: "{{ .Values.env.SPRING_DB_HOST }}"
            - name: SPRING_DB_PORT
              value: "{{ .Values.env.SPRING_DB_PORT }}"
            - name: SPRING_DB_NAME
              value: "{{ .Values.env.SPRING_DB_NAME }}"
            - name: SPRING_DB_USER
              value: "{{ .Values.env.SPRING_DB_USER }}"
            - name: SPRING_DB_PASSWORD
              value: "{{ .Values.env.SPRING_DB_PASSWORD }}"
          resources: {{- toYaml .Values.resources | nindent 12 }}  # Recursos asignados al contenedor