apiVersion: v1
kind: Service
metadata:
  name: backend 
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.service.port }} # Puerto a exponer
      targetPort: 8080 # Puerto de la aplicación
  type: {{ .Values.service.type }} # Tipo de servicio 