- import_tasks: dependencies.yml  # Primero las dependencias

- name: Esperar a que APT esté libre
  shell: |
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      echo "Esperando a que se libere el lock de APT..."
      sleep 2
    done
  args:
    executable: /bin/bash

- name: Instalar PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Habilitar PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Crear usuario y base de datos
  become_user: postgres
  shell: |
    psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ db_user }}'" | grep -q 1 || psql -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';"
    psql -lqt | cut -d \| -f 1 | grep -qw {{ db_name }} || psql -c "CREATE DATABASE {{ db_name }} OWNER {{ db_user }};"
  args:
    executable: /bin/bash

- name: Deploy postgresql.conf from template
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/12/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL

- name: Deploy pg_hba.conf from template
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/12/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'
  notify: Restart PostgreSQL

- import_tasks: firewall.yml  
